### PR TITLE
Add Oracle Start Guide document

### PR DESCRIPTION
**Pull request by mickeypearce**
Simple quickstart guide: https://github.com/mtxr/vscode-sqltools/pull/133

### CODE REVIEW

**Comment by mtxr** [comment]
:1st_place_medal: Awesome!

**Comment by mtxr** [comment]
@mickeypearce did you try the latest version?

**Comment by mickeypearce** [comment]
Sweet! It works. I saw you added an enabling setting for Node runtime. :+1:

**Comment by mtxr** [comment]
Yes,

I was afraid to break compatibility for existing users.
New users will follow the guide, so they will notice the setting and the whole setup process.
Thanks for you help @mickeypierce!
Matheus Teixeira

**Pull request merged**
