### PR TITLE
Implement drag and drop objects

### PR DESCRIPTION
**Pull request by ScriptPup**
PR implementing requested object-name drag and drop functionality requested in #1135 & [#10](https://github.com/ScriptPup/sqltools-teradata-driver/issues/10).

Dragging resource groups does nothing (as they are just logical containers and mean nothing to the underlying SQL engine).

efe6d2a6-70cf-4976-a5aa-3e38d924b328

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You have made the needed changes to the docs (N/A)
- [x] You have written a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by ScriptPup** [comment]
I meant to mention in the PR, but forgot - The new feature will not work until version `1.78` is released (or using the insider's build).

That being said, I did test on `1.77` and there are no breaking changing due to this feature. The functionality will simply be latent until VSCode's underlying bugs are fixed in `1.78`.

**Comment by ScriptPup** [comment]
Confirmed today that this enhancement works with the updated production 1.78 release of VSCode.

**Comment by emil14** [comment]
Can we merge this one?

**Comment by bombillazo** [comment]
Hello @mtxr , can this be reviewed and merged if ok?

**Review by gjsjohnmurray — APPROVED** [review]
Thanks for contributing this.

**Pull request merged**
