### PR TITLE
Add `sqltools.results.showConsoleOnError` setting

### LINKED ISSUE #1365: Option to Disable Automatic Error Console Opening on Query Errors
image

I would like to request a feature to disable the automatic opening of the error console when there is an error in an SQL query. Currently, the error console opens every time there's an issue, even though the error message is already displayed in the result tab. This behavior is disruptive and cumbersome.

It would be greatly beneficial to have a setting in SQLTools that allows users to control this behavior, enabling them to choose whether or not the error console should open automatically on query errors. This feature would enhance the user experience by reducing unnecessary interruptions.

Thank you for considering this feature request.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #1365

### CODE REVIEW

**Review by 818Nawaf — APPROVED** [review]

**Review by 818Nawaf — APPROVED** [review]

**Review by 818Nawaf — APPROVED** [review]

**Comment by 818Nawaf** [comment]
> هذا PR يصلح #1365

**Review by george-james-software — APPROVED** [review]

**Comment by 818Nawaf** [comment]
I agree to this withdrawal request‫أُرسلت من الـ iPhone‬‫في 27‏/08‏/2024 الساعة 1:45 ص، كتب/كتبت ‏818Nawaf ***@***.***>***@***.*** approved this pull request.



In packages/plugins/connection-manager/webview/results.ts:
> @@ -122,7 +122,7 @@ class ResultsWebview extends WebviewProvider<ResultsScreenState> {
       this.title = `${prefix}: ${suffix}`;

**Comment by 818Nawaf** [comment]
I agree to this withdrawal request‫أُرسلت من الـ iPhone‬‫في 27‏/08‏/2024 الساعة 1:47 ص، كتب/كتبت ‏818Nawaf ***@***.***>:‬﻿
@818Nawaf approved this pull request.

**Comment by 818Nawaf** [comment]
I agree to this withdrawal request‫أُرسلت من الـ iPhone‬‫في 27‏/08‏/2024 الساعة 3:59 ص، كتب/كتبت ‏818Nawaf ***@***.***>:‬﻿
@818Nawaf approved this pull request.

**Pull request merged**
