### PR TITLE
Intellisense

### PR DESCRIPTION
**Pull request by julientype**
Generate code offer the best way to setup templates ..... in sqlite

example.....
PRAGMA integrity_check;

right click the database and the menu popups......
all you do is run the script.......

 PRAGMA foreign_key_check;

 you just need to create the menus and automate the scripts  with some logic......

no joke    begin-stmt:     <--a menu
pragma-stmt:<--- a menu

basically you simple load sample up  to build with..... 
  
https://www.sqlite.org/pragma.html#syntax

samples can be long ....... they are samples  you dont run the script you copy past from it .....

### CODE REVIEW

**Comment by julientype** [comment]
the hard part Of  SQL is learning the syntax....   once you understand it intelligence become easy
 so by setting up menus correctly you simply insert sql samples   easy to update  or improve on wizards for script types .... like build a view with sub tables.....   first setup basic menus the work on wizards  that can auto fill your request....  <-a bit harder to setup...... yet samples are simple basic layouts  for wizards....

**Comment by mtxr** [comment]
Amazing! thanks @julientype !

I'll take a look at this. I was working on something similar to extend the parser to other languages, but it's very hard. I believe it's okay to release it for SQLite first.

Great job!

**Comment by mtxr** [comment]
Related to #110

**Comment by mtxr** [comment]
Will restart another branch

**Pull request closed without merging**
