### PR TITLE
Steg0/executecurrent

### PR DESCRIPTION
**Pull request by steg0**
This is my version of the original 'executecurrent' implementation done by @vrokolos .

Main change (over my initial approach as well) is, it tries to use the existing query splitter to find the query at the cursor.
I've been testing this in my daily work (with DB2 mainly) and it works alright for me. So I guess it's time to hear what other people have to say.

### CODE REVIEW

**Comment by mtxr** [comment]
@steg0 thanks!

I'll test it today with PostgreSQL, MySQL and SQLite.
Also, we can release this under a experimental setting, so users can enable and disable it for testing.

**Comment by mtxr** [comment]
PR will close #277

**Comment by mtxr** [comment]
It's seems to be working pretty well!

I'm adding a decoration to highlight the query that will be executed.

See:
Peek 18-01-2020 10-10


It's in the very beginning, but together with your code, it will be a killer feature!

**Comment by vinclei** [comment]
Hey @mtxr , @steg0 - this looks good, wondering how to use this feature? 
I can't find this in the command palette..

**Pull request merged**
