### PR TITLE
[Fix][#72][#799][#1264]Not able to connect to AWS RDS postgresql

### PR DESCRIPTION
**Pull request by jqknono**
Fix not able to connect to AWS RDS Postgresql

----

- Changed the default setting schema.
- Tested on Windows & Linux.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Is this changing the default behaviour of the driver, making it less secure?

My understanding of https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener is that we should only pass `"rejectUnauthorized": false` if the user explicitly opts for this.

Isn't it sufficient to add `"default": true` to the definition of `rejectUnauthorized` in connection.schema.json?

**Comment by gjsjohnmurray** [comment]
Thanks for making the changes. I noticed you have left the property required. Is this necessary?

**Comment by jqknono** [comment]
> Is this changing the default behaviour of the driver, making it less secure?
> 
> My understanding of https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener is that we should only pass `"rejectUnauthorized": false` if the user explicitly opts for this.
> 
> Isn't it sufficient to add `"default": true` to the definition of `rejectUnauthorized` in connection.schema.json?

Yes, you're right. I revert the changing of `rejectUnauthorized`, it's now default "true".
Tested both Windows/Linux.
image

**Comment by jqknono** [comment]
> Thanks for making the changes. I noticed you have left the property required. Is this necessary?

`required` is not necessary, I just removed it.

**Review by gjsjohnmurray — APPROVED** [review]
Thanks for the PR

**Pull request merged**
