### PR TITLE
Add "Getting Started" to home

### PR DESCRIPTION
**Pull request by richb-hanover**
As a relative newcomer to VScode, I had a hard time understanding how SQLTools "worked" in the VScode ecosystem.

I felt your documentation was missing a description of how to get started. (I have to compliment you - the actual installation process is _flawless_, once I learned where to look.)

Here's an introductory paragraph that would have been a useful hint for me. Thanks!

Describe here what is this PR about and what we are achieving merging this.

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [ x ] Your code builds clean without any errors or warnings
- [ x ] You have made the needed changes to the docs
- [ x ] You have written a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by archiewood** [comment]
(Agree - this also confused me initially)

**Comment by gjsjohnmurray** [comment]
Thanks for your PR. Here are some suggestions:

1. Use the term "VS Code" instead of "VScode".
2. Instead of pointing the user to Marketplace, tell them to go to VS Code's Extensions view (a textual way is to run `View: Show Extensions` from Command Palette), then enter the search text `@tag:sqltools-driver`, then install the driver they need. A dependency will cause the core SQLTools extension to get installed too.
3. We don't want the official documentation to link to 3rd-party YouTube videos.

**Comment by richb-hanover** [comment]
> 1.    Use the term "VS Code" instead of "VScode".

Yes. I was confused about this, but in the Visual Studio site, Microsoft says, "By using VS Code, you agree to its license and privacy statement..." I'll update

> 2.    Instead of pointing the user to Marketplace, tell them to go to VS Code's Extensions view (a textual way is to run View: Show Extensions from Command Palette), then enter the search text @tag:sqltools-driver, then install the driver they need. A dependency will cause the core SQLTools extension to get installed too.

I updated this as well. I'll note that this procedure hides all the good work that you've done to make the installation process flawless. (My earlier instructions just say "Go to Marketplace; Install SQLTools; Install your driver; Create the connection" and you're on the air.)

> 3.    We don't want the official documentation to link to 3rd-party YouTube videos.

I get it. You should consider making your own video - it really helps newcomers get started.

Thanks!

**Review by gjsjohnmurray — APPROVED** [review]
Thanks!

**Comment by richb-hanover** [comment]
I'm feeling dopey here... It looks as if you have merged the "Getting Started" section into `mtxr:dev`, but I don't see it on the main README file. What am I missing? 

Oh, wait! I just figured it out. The main README and home.mdx in the _/docs/..._ directory need to be kept in sync... 

What's the best way to patch this up? Many thanks!

**Comment by richb-hanover** [comment]
And the answer (to "What's the best way to patch this up?") is #1240 Thanks again.

**Pull request merged**
