### PR TITLE
[Feature] Add 'none' option to location to skip showing query result

### LINKED ISSUE #1158: `None` result location
**Is your feature request related to a problem? Please describe.**

First off, great tool, thanks for this!

This request is to prevent a query result window from opening. This is useful when running setup or idempotent update scripts, and one has a fixed dev layout that is inevitably altered when running a script from the IDE. Currently, one can customize somewhat how the result window is opened:

image

**Describe the solution you'd like**

Add a `None` option so that when one runs a query, no new result location window is opened. 

**Describe alternatives you've considered**

N/A

### PR DESCRIPTION
**Pull request by bombillazo**
Resolves #1158 

This request is to prevent a query result window from opening. This is useful when running setup or idempotent update scripts, and one has a fixed dev layout that is inevitably altered when running a script from the IDE.

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You have made the needed changes to the docs
- [x] You have written a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by bombillazo** [comment]
Hey @gjsjohnmurray @george-james-software @mtxr, I am submitting this PR for your consideration and review to resolve the related issue #1158 . Thanks!

**Comment by bombillazo** [comment]
Any thoughts on this? Does it look ok to merge?

**Comment by gjsjohnmurray** [comment]
Please update your branch from `dev` to fix the CI failure (#1167 is related)

**Comment by bombillazo** [comment]
@gjsjohnmurray Done.

**Review by gjsjohnmurray — APPROVED** [review]
Thanks for the contribution.

**Comment by bombillazo** [comment]
Quick question, how often is the published release updated?

**Comment by gjsjohnmurray** [comment]
> Quick question, how often is the published release updated?

I'm working on one now.

**Pull request merged**
