### PR TITLE
Use gethue as sql parser for autocomplete context

### PR DESCRIPTION
**Pull request by smaspe**
By replacing `node-sql-parser` with `gethue`, the autocomplete context is more complete, and provides more accurate information to the drivers.

See issue #754

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] ~~You have made the needed changes to the docs~~ no change needed
- [x] You have written a description of what is the purpose of this pull request above

https://user-images.githubusercontent.com/4571256/104316963-8ae98f00-54dd-11eb-9edc-839e3a570789.mov

### CODE REVIEW

**Comment by mtxr** [comment]
This is awesome! I'll take a look at this over the weekend

**Comment by bruwozniak** [comment]
@mtxr any chance of this getting merged? Right now we are using custom build to get this feature. Furthermore, let me ask frankly: is this project still maintained?

**Comment by mtxr** [comment]
I do this tonight, for sure. I also need to release a new version.

about the project being maintained, hard to tell.. I want a lot to get back to the track here, but with covid, my wife and I have been spending a lot of time helping my kid with school, so I'm not able to put the effort I want in the project like I could before

**Comment by bruwozniak** [comment]
Appreciate your response @mtxr ! I feel you, hopefully in few months things will be more stable, we all need it. Thanks for the great project though

**Pull request merged**
