### PR TITLE
WIP: Lots of changes. Please read comments

### PR DESCRIPTION
**Pull request by vrokolos**
Added a command to run query under cursor position as long as it's surrounded by blank lines #277
Added a command to describe the object-word (table only currently) under the cursor position on any editor
Created another dialect for oracle where only the current schema objects are retrieved. This makes it a lot faster. Also optimized and recreated from scratch all the sqls for retrieving metadata.

### CODE REVIEW

**Comment by vrokolos** [comment]
Fixed the commands position in package json.
Also added first release of bind parameter support for oracle.
I had a problem with the api.d.ts file had to rename it to .ts for some reason

**Comment by mtxr** [comment]
@vrokolos thanks!

I'll review it tonight after work! Reach you back if needed some changes

**Comment by vrokolos** [comment]
I added a new command GetDDL that will output the DDL script for the current object on a new tab. That includes tables, functions, packages and everything else in oracle. Only did it for oraclelocal though. Someone needs to implement it for other dialects.

Fixed some bugs on the metadata queries and made them faster for oraclelocal.

The previewlimit now works for all queries (except the metadata ones) on the oracle dialect. Not just the showrecords one

**Comment by vrokolos** [comment]
Completely replaced ReactTable with SlickGrid => ALOT faster results table.
Automatically add parameter default values when query is run without parameter values so that user can change them.
Had problem with oracle date type on bind parameters so replace the type with string temporarily.
DescribeCurrent command now shows table columns, data and DDL script on separate tabs.
Store bind parameter values on global cache so that they are automatically used next time the same parameter name is found.
Fixed bugs!

**Comment by vrokolos** [comment]
Adding issues affected by this pull request:
#265 #261 #277

**Comment by mtxr** [comment]
Awesome!

**Comment by mtxr** [comment]
@vrokolos I'm starting to review and test it right now. I'll extends your changes to other dialects too

Great job!

**Comment by mtxr** [comment]
@vrokolos is there any other option for slickgrid? the project seems to be abandoned. That can affect the maintenance and compatibility of this project. Also I saw we are not supporting vscode color scheme to match user's color scheme.

I was planning to switch to one of this libs, but I didn't have time to do it yet:
- https://adazzle.github.io/react-data-grid/docs/examples/simple-grid
- https://devexpress.github.io/devextreme-reactive/react/grid/
- https://www.ag-grid.com/example.php#/

I want to test both first.

**Comment by vrokolos** [comment]
Not sure but I've been using slickgrid a lot and had no problems with it but yes you are right about the color theme. Maybe add an option about what grid to use since it is easily doable until people get to use all of them and see how it goes from there

**Comment by mickeypearce** [comment]
Hey @vrokolos ,
I tested "Run current query" and it works fine. :+1: 

I have some problems with "Describe Current Object".  Can you please explain what is "current" in this case? Is it a selection or a line parse...
I tried on a simple table (no complex types) and I get "ORA-01036: illegal variable name/number".

**Comment by vrokolos** [comment]
I think I fixed that in latest commits. Will retest later

**Comment by mickeypearce** [comment]
> Added a command to run query under cursor position as long as it's surrounded by blank lines #277
> Added a command to describe the object-word (table only currently) under the cursor position on any editor
> Created another dialect for oracle where only the current schema objects are retrieved. This makes it a lot faster. Also optimized and recreated from scratch all the sqls for retrieving metadata.

Could it be merged with an existing dialect so they wouldn't be two?

**Comment by vrokolos** [comment]
One dialect. Need property local set to true for eingle scheme

**Comment by vrokolos** [comment]
The error probably occurs because you're not using local=true and the old queries need changing

**Comment by mickeypearce** [comment]
Is "local" missing in package.json?

**Comment by vrokolos** [comment]
Here's the thing. On the old multi-schema queries ":table" is used to reference the table but "table" is a reserved word on oracle and you can't use it for a variable name so I changed it to something else on the single-schema queries I think ":thetable". Now we're using bindable parameters and not replaceable ones and it throws an exception on ":table". Need to change the old queries.

The "local" option I put it in temporarily since @mtxr  should name it as he chooses :)

**Comment by mtxr** [comment]
@vrokolos I started to replace react-table as you suggest by dx-react-grid. Slickgrid looks fine, but it lacks of some features that we currently have and lacks also of some features I'm looking forward to add.

I did some benchmarks with that libraries and slickgrid and dx-react-grid is awesome.

Don't worry that I'll adapt this to your PR as soon as I finish doing theme changes.

You can see a preview of the benchmark here:
https://github.com/mtxr/vscode-sqltools/pull/297#issue-299732714

**Comment by vrokolos** [comment]
If it works ok then great!
Is it virtualised like slickgrid? You don't need paged results in slickgrid since it automatically creates virtual pages and it can handle millions of records without any loss of speed.
Was searching for one myself. Could use this in my projects if it can do that

**Comment by mtxr** [comment]
@vrokolos yes it does. We can do both. I'll add an option to disable pagination and use virtual scrolling but by default I'll keep as is. Even with slickgrid I got some slowness using it when scrolling very fast. So I'll test it better. But having an option is not a big deal

**Comment by mtxr** [comment]
I've added react-grid to master branch. Can you update your branch? Please, consider every change i've made on ui pakage

**Comment by vrokolos** [comment]
I'm on vacation for the next three weeks so it will take some time

**Comment by mtxr** [comment]
@vrokolos can we talk someday next week? 

I see many changes all together and this is making it hard to test. There are some stuff that's not working well here when I'm testing with other dialects, so I would like to get more information about it to try to use the same strategy you did for other dialects.

What do you think?

**Pull request closed without merging**
