### PR TITLE
Oracle: Add PK and FG properties

### PR DESCRIPTION
**Pull request by mickeypearce**
- added isPK and isFG property
- changed tables select to only tables owned by current user (https://github.com/mtxr/vscode-sqltools/issues/139). Selecting for all tables with addition to joining with constraints info takes quite some time for larger databases.
- bacground property in the tasks.json was in the wrong place
- fetch date and clob datatypes as string

@mtxr , icons are not visible in my case, is there anything else i should do to display them? Also when connecion is active, there is an icon missing in my case.

### CODE REVIEW

**Comment by mtxr** [comment]
Thanks for the fast PR!

About the icons, can you attach a screenshot? Just the new icons or any icon?

Try to use VSCode developer tool to check the icons path. Seems to be a path issue at first.

The way the code is, it should work. I saw the file changes. Should be working for sure.

**Comment by mtxr** [comment]
This PR Closes #139 ? If it closes, would be nice cause we could keep only #71 for all this change.

**Comment by mickeypearce** [comment]
image
Active connection is "test"

**Comment by mtxr** [comment]
What do you see in dev tools?

**Comment by mtxr** [comment]
I'll merge. This code looks great. It's probably some compilation issue

**Pull request merged**
