### PR TITLE
Add Google Cloud SQL (PostgreSQL) driver to list

### PR DESCRIPTION
**Pull request by chokoswitch**
Adds an extension driver for Google Cloud SQL (PostgreSQL) to the community drivers list

https://marketplace.visualstudio.com/items?itemName=curioswitch.sqltools-driver-cloudsql-pg

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Please also add your entry to docs/src/pages/en/drivers/drivers-table.mdx

**Comment by gjsjohnmurray** [comment]
@chokoswitch please make the additional edit I requested

**Comment by chokoswitch** [comment]
Sorry for the huge delay on this, added to docs page

**Review by gjsjohnmurray — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
Thanks for your contribution.

**Pull request merged**
