### PR TITLE
Multiple MSSQL driver improvements

### PR DESCRIPTION
**Pull request by fzhem**
Describe here what is this PR about and what we are achieving merging this.

- Use Microsoft recommended system table to get a list of databases
- Better error handling: Throw database configuration errors rather than retrying
- Set default connection timeout to 15 - same as the tedious driver
- Add tedious specific option - trustServerCertificate
----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [ ] Your code builds clean without any errors or warnings
- [x] You have made the needed changes to the docs
- [x] You have written a description of what is the purpose of this pull request above

### CODE REVIEW

**Review by Deltanji — APPROVED** [review]

**Review by Deltanji — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
@fzhem thanks for this PR. Fixes for a CI issue were merged into mtxr:dev earlier today. Please update fzhem:dev with them, then I will allow CI to run on this PR.

**Comment by fzhem** [comment]
> @fzhem thanks for this PR. Fixes for a CI issue were merged into mtxr:dev earlier today. Please update fzhem:dev with them, then I will allow CI to run on this PR.

Cheers dude! I've just synced the fork.

**Review by gjsjohnmurray — APPROVED** [review]
Thanks. I will merge this, but I don't yet know when we will be doing the next release.

**Comment by gjsjohnmurray** [comment]
This is in today's release.

**Pull request merged**
