### PR TITLE
WIP: Add Cassandra driver

### PR DESCRIPTION
**Pull request by EpicEric**
This PR adds support to Cassandra and any other databases that use CQL into SQLTools, and adds documentation on the setup.

This has been tested with both Cassandra and Scylla instances.

### CODE REVIEW

**Comment by EpicEric** [comment]
Apparently there are some issues with the code, I'll close the PR for now and reopen after they're done.

**Comment by mtxr** [comment]
AWESOME! I didn't even documented the new UI changes nor updated the tutorial but you followed all the required patterns. Thanks @EpicEric 


Merging...

**Comment by mtxr** [comment]
@EpicEric  Can I assign futures issues for Cassandra to you?

I'm looking for maintainers for each driver. That would help me a lot

**Comment by EpicEric** [comment]
No problem. You can assign them to me.

**Pull request merged**
