### PR TITLE
[Feature] TiDB driver and ssl options support

### PR DESCRIPTION
**Pull request by Icemap**
Describe here what is this PR about and what we are achieving merging this.

Issue Tag: https://github.com/mtxr/vscode-sqltools/issues/1112

1. Support TiDB via MySQL driver.
2. Update the `mysql` lib to the `mysql2`.
3. Support SSL options in the `Connection Assistant` panel.

image
image
image

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You have made the needed changes to the docs
- [x] You have written a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by Icemap** [comment]
For docs aspect screenshot:

Build way:

```shell
cd docs
yarn
yarn dev
```

- Home Page: The picture is broken because it is linked to the GitHub repository. So if this PR is merged, the picture will be fine:

    image

- TiDB driver page:

    image
    image
    image
    image

- README.md

    image

**Comment by Icemap** [comment]
Hi, @gjsjohnmurray. I support the SSL option and TiDB driver in this PR. PTAL. Thanks.

**Comment by gjsjohnmurray** [comment]
@Icemap I have updated this PR's branch from dev and done some rudimentary testing. Please re-test and let me know here. I might not be able to respond immediately, so please continue to be patient as we inch towards getting this merged.

**Review by gjsjohnmurray — APPROVED** [review]
Approving and merging

**Pull request merged**
