### PR TITLE
feat: give ability to set `connectString` directly

### PR DESCRIPTION
**Pull request by zetxx**

### CODE REVIEW

**Comment by mickeypearce** [comment]
Hey @zetxx , thanks for PR.
https://github.com/mtxr/vscode-sqltools/blob/cc3e97b7a067300a8d560fabe11231b9a753ac99/packages/core/dialect/oracle/index.ts#L55-L57

Now it is possible if you ommit the `this.credentials.server` and `this.credentials.port`, the connectionString maps directly from `this.credentials.database`.

I agree, maybe it is not super clear.

**Comment by mtxr** [comment]
@zetxx you should add this configuration to packages/extension/package.json and ConnectionInterface too.

Could you do that please?

**Comment by mtxr** [comment]
@mickeypearce I believe his suggestion worth. Connection string are very used and we should have a explicit way to do that to avoid confusion. I could add it to other dialects too since now it's working just for oracle.

What do you think?

**Comment by mickeypearce** [comment]
I agree, having connectString explicitly is much clearer. Let's do it.

**Comment by zetxx** [comment]
do i need to do something more ?

**Comment by mtxr** [comment]
No, that's on me now.
I'll add the same feature for other dialects and release it.

Thanks @zetxx! Welcome too the community!

**Pull request merged**
