### PR TITLE
Add Databricks driver

### PR DESCRIPTION
**Pull request by fjakobs**
Databricks Driver for SQLTools published to Marketplace at https://marketplace.visualstudio.com/items?itemName=databricks.sqltools-databricks-driver

This PR updates the document and adds Databricks driver as a community driver.

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You have made the needed changes to the docs
- [x] You have written a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@fjakobs thanks for this PR. I'll be happy to approve and merge it as soon as you say it's no longer Draft.

**Comment by fjakobs** [comment]
Thanks @gjsjohnmurray. I'll just waiting for the driver to hit the marketplace. Will update the PR once it's there.

**Comment by fjakobs** [comment]
I've pushed the Databricks driver to the VSCode marketplace. The PR can be merged.

https://marketplace.visualstudio.com/items?itemName=databricks.sqltools-databricks-driver&ssr=false#overview

**Review by gjsjohnmurray — APPROVED** [review]
Thanks!

**Pull request merged**
