### PR TITLE
Add new Related Tools table with Markdown SQL and PRQL Pro Tools info and links to docs

### PR DESCRIPTION
**Pull request by RandomFractals**
This PR includes changes for the new SQL Tools related VS Code extensions as described in https://github.com/mtxr/vscode-sqltools/issues/1200#issuecomment-1684924198

I used simple icon, Name, Download and Repository table headers for the new Related Tools table in docs:

sql-tools-related-tools

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@mtxr @george-james-software what do you both think about this? I have requested reviews from you as a way of getting your feedback.

**Review by gjsjohnmurray — COMMENTED** [review]
Maybe in place of the "Download" and "Repository" columns the "Related Tools" table should have a single column captioned "Homepage" or "Details" or something like that.

**Comment by RandomFractals** [comment]
The Download and Repository links are different:

- Download in our case links to the GitHub sponsorship tier page to Sign up for access to those premium VS Code extensions.
- Repository could be renamed to Documentation and links to the documentation page of the related tool.

Free and open source Related Tools added to this section later on can use Download to link to the GitHub release with attached extension `.vsix` package or versions page in VS Code marketplace, or a custom related tool download page. I wanted to keep that part flexible.

Willing to rename both columns to something more descriptive provided the reasoning above, but I think both are required for clarity and easy install/docs links to navigate.

**Comment by RandomFractals** [comment]
I actually like how your drivers table only has Driver and Links columns.

Maybe we should change it to this format with Tool and Links columns to reach consensus on this new Related Tools table docs section addition:

sqltools-drivers-table

**Comment by RandomFractals** [comment]
On a related note, I recently tested all of my data viz, new pro data tools and your SQL Tools extensions in the latest version of Azure Data Studio. Interestingly enough, Azure Data Studio, being a custom IDE built using VS Code code base, is not connected to the VS Code marketplace for extensions, and doesn't use https://open-vsx.org/ registry, but now allows extension authors to submit their extensions to their extensions gallery.

I think we should submit SQL Tools to be included in the Azure Data Studio extensions gallery, as many data analysts are starting to use it now, but that IDE only provides access to the Azure supported data sources.

They do require a `Download` link for an extension to be listed in their extensions gallery. Just wanted to provide this extra context info. Can open new ticket for us to work on that submission too, as we plan to submit some of our data related tools to be included in their custom extensions gallery for the data folks using Azure Data Studio.

Docs: https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/extension-authoring?view=sql-server-ver16#publish-an-extension

P.S.: we did confirm that SQL Tools now work in the latest Azure Data Studio verision. See this X post for more info: 

https://twitter.com/TarasNovak/status/1691780002218479728

duckdb-sql-tools-in-azure-data-studio

**Review by gjsjohnmurray — DISMISSED** [review]

**Review by gjsjohnmurray — APPROVED** [review]

**Comment by RandomFractals** [comment]
@gjsjohnmurray appreciate you merging this SQL Tools extras PR!

**Pull request merged**
