### PR TITLE
Add ability to specify a folder for session files

### PR DESCRIPTION
**Pull request by Fmstrat**
Addresses https://github.com/mtxr/vscode-sqltools/issues/497

Adds the ability to specify a folder for session files to be saved in when hitting `Ctrl-S` vs the root of the repo.

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [X] Your code builds clean without any errors or warnings
- [X] You have made the needed changes to the docs
- [X] You have wrote a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by Fmstrat** [comment]
Hrm, I think the checks are failing because I'm not assigned to the issue maybe?

**Comment by mtxr** [comment]
Great job @Fmstrat !

Thanks!

**Comment by Fmstrat** [comment]
@mtxr Thanks for the merge! Any idea when v0.22 will hit release?

**Comment by mtxr** [comment]
Still working on it. You can check branch *lazy-tree*, but basically just
postgres driver is up to date. I'm using with to develop all features
before spread to other drivers.

That branch we have a lot of enhancements to explorer, completions are
working pretty well and there are a lot of other improvements too.

But no release date yet. After this release I hope we can get fast releases
back again because the project will be better prepared for contributions.

Funny thing... there will be no v0.22, we will jump to v1.0.x :D

**Pull request merged**
