### PR TITLE
remove version of hana-client - use latest

### PR DESCRIPTION
**Pull request by ariel-bentu**
as discussed - using latest version. related to issue #252

----

Thank you for your contribution! 
Before submitting this PR, please make sure:

- [ ] Your code builds clean without any errors or warnings
- [ ] You have made the needed changes to the docs
- [ ] You have wrote a description of what is the purpose of this pull request above

### CODE REVIEW

**Comment by mtxr** [comment]
@ariel-bentu  Can't we keep a desired version?
Getting rid of a fixed version completely will cause errors for breaking changes as they release. I thought you wanted to update the version number in the code to the latest existing after testing.

Let me know if you have reasons to get rid of it. But in a first sight this looks an overkill

**Comment by ariel-bentu** [comment]
@mtxr, I know that the typical best practice is to depend on specific version, that was tested with your code etc.
in this case, I would argue, the best practice is not a fit. the driver of the DB (in this case SAP HANA) should be used to access all DB versions that are out there - since sql-tools is not tied to a specific DB version but should support all of them. as such, new DB versions may require the latest version of the driver. Drivers are backwards compatible (at least SAP HANA's is).

The alternative would be to allow the vscode user to specify the version they want to use. this you may consider adding, but even then I would opt for latest version, with the ability of the vscode user to overwrite by settings.

What do you say?

**Comment by ariel-bentu** [comment]
@mtxr - what do you say?
Thanks

**Comment by mtxr** [comment]
Go for it.

I have a plan for the drivers, I'm still writing the requirements before
changing it, but for now you can move forward. We won't be fixing versions
for the other drivers as well with the new arch.

**Comment by ariel-bentu** [comment]
ok thanks. I see "missing assignee" error in the PR - should I do something?

**Comment by mtxr** [comment]
Just needed to assign this PR to you. I've already done it, thanks

**Pull request merged**
